# Generated by Django 3.1.2 on 2020-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(default='test', editable=False, max_length=30),
        ),
    ]
