# Generated by Django 3.1.2 on 2020-10-22 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201022_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 22), editable=False),
        ),
    ]
