# Generated by Django 3.1.2 on 2020-12-01 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20201022_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 8, 42, 1, 751082, tzinfo=utc), editable=False),
        ),
    ]
