# Generated by Django 3.1.2 on 2020-12-02 12:47

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=30, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='')),
            ],
        ),
    ]
